import type { Caption } from "@remotion/captions";
import voiceoverWords from "./voiceover-words.json";

export const FPS = 30;
export const WIDTH = 1080;
export const HEIGHT = 1350;

const SCENE_NAMES = {
  s0: "Scene 0 · Hook",
  s1: "Scene 1 · Meet Amina and Lukas",
  s2: "Scene 2 · The problem",
  s3: "Scene 3 · Meet pacs.008",
  s4: "Scene 4 · The twist",
  s5: "Scene 5 · T2",
  s6: "Scene 6 · Lukas gets paid",
  s7: "Scene 7 · Recap",
  s8: "Scene 8 · Call to action",
} as const;

type AlignedWord = {
  scene: keyof typeof SCENE_NAMES;
  text: string;
  startMs: number;
  endMs: number;
};

/**
 * The recorded voiceover (public/voiceover/ep01.mp3), word by word.
 * Generated by scripts/align_voiceover.py: the script's spelling (script.json)
 * with the recording's timing (speech recognition, see README).
 */
const WORDS = voiceoverWords as AlignedWord[];

// A scene starts just before its first word (never before the previous scene's
// last word ends); the last scene holds a moment after the final word.
const LEAD_S = 0.15;
const TAIL_S = 1.8;
const sceneIds = Object.keys(SCENE_NAMES) as Array<keyof typeof SCENE_NAMES>;
const firstStart = (id: string) =>
  WORDS.find((w) => w.scene === id)!.startMs / 1000;
const lastEnd = (id: string) =>
  [...WORDS].reverse().find((w) => w.scene === id)!.endMs / 1000;
const starts = sceneIds.map((id, i) =>
  i === 0
    ? 0
    : Math.max(lastEnd(sceneIds[i - 1]) + 0.05, firstStart(id) - LEAD_S),
);

/** Scene windows in seconds, derived from the voiceover. */
export const SCENES = Object.fromEntries(
  sceneIds.map((id, i) => [
    id,
    {
      start: starts[i],
      end: i + 1 < sceneIds.length ? starts[i + 1] : lastEnd(id) + TAIL_S,
      name: SCENE_NAMES[id],
    },
  ]),
) as Record<
  keyof typeof SCENE_NAMES,
  { start: number; end: number; name: string }
>;

export type SceneId = keyof typeof SCENES;

export const sceneFrom = (id: SceneId) => Math.round(SCENES[id].start * FPS);
export const sceneDuration = (id: SceneId) =>
  Math.round((SCENES[id].end - SCENES[id].start) * FPS);
export const TOTAL_FRAMES = sceneFrom("s8") + sceneDuration("s8");

const ENDS_PHRASE = /[.,:;!?…]["”’]?$/;

/** Every spoken word, in order: the burned-in captions. */
export const VOICEOVER: Caption[] = WORDS.map((w, i) => ({
  text: ` ${w.text}`,
  startMs: w.startMs,
  endMs: w.endMs,
  timestampMs: w.startMs,
  confidence: 1,
  pageBreakAfter: ENDS_PHRASE.test(w.text) || WORDS[i + 1]?.scene !== w.scene,
}));

const WORDS_BY_SCENE = Object.fromEntries(
  sceneIds.map((id) => [id, VOICEOVER.filter((_, i) => WORDS[i].scene === id)]),
) as Record<SceneId, Caption[]>;

const normalize = (s: string) =>
  s
    .toLowerCase()
    .replace(/^[^a-z0-9]+/, "")
    .replace(/[^a-z0-9]+$/, "");

/** Frame, relative to the scene start, at which `word` starts being spoken. */
export const cue = (scene: SceneId, word: string, nth = 0): number => {
  const matches = WORDS_BY_SCENE[scene].filter(
    (c) => normalize(c.text) === normalize(word),
  );
  const match = matches[nth];
  if (!match) {
    throw new Error(`Word "${word}" (#${nth}) not found in ${scene}`);
  }
  return Math.round((match.startMs / 1000) * FPS) - sceneFrom(scene);
};

/** Frame, relative to the scene start, for an absolute time in seconds. */
export const at = (scene: SceneId, seconds: number) =>
  Math.round(seconds * FPS) - sceneFrom(scene);
